package J;
import static J.Koneksi.newkoneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author Widhua
 */
public class FormDMhs extends javax.swing.JFrame {
    DefaultTableModel TM = new DefaultTableModel();

    /**
     * Creates new form FormDMhs
     * @throws java.sql.SQLException
     */
    public FormDMhs() throws SQLException {
        initComponents();
        jTable2.setModel(TM);
        TM.addColumn("ID");
        TM.addColumn("NAMA");
        TM.addColumn("ALAMAT");
        TM.addColumn("ASAL_SMA");
        TM.addColumn("TELEPON");
        
        this.setTitle("APLIKASI PENDAFTARA");
        ImageIcon IC = new ImageIcon("img/nopic.jpg");
        this.setIconImage(IC.getImage());
        
        List_All();
        kosongkanform();
        loadphoto("");
    }
    
    private void loadphoto(String idx){
        String nopic = "src/img/nopic.jpg";
        String ph = "src/img/"+idx+".jpg";
        System.out.println(ph);
        BufferedImage photopendaftar = ImptImage.InputImage(ph);
        if(photopendaftar == null){
            photopendaftar = ImptImage.InputImage(nopic);
        }
        ImageIcon iconphoto = new ImageIcon(photopendaftar);
        photo.setIcon(iconphoto);
    }
    
    private void List_All() throws SQLException{
        TM.getDataVector().removeAllElements();
        TM.fireTableDataChanged();
        
        Connection cnn = newkoneksi();
        if( !cnn.isClosed() ){
            
            String sql = "SELECT * FROM daftar;";
            PreparedStatement PS = cnn.prepareStatement(sql);
            ResultSet rs = PS.executeQuery();
            while( rs.next() ){
                Object[] dta = new Object[5];
                dta[0] = rs.getString("ID");
                dta[1] = rs.getString("NAMA");
                dta[2] = rs.getString("ALAMAT");
                dta[3] = rs.getString("ASAL_SMA");
                dta[4] = rs.getString("TELEPON");
                TM.addRow(dta);
            }
        }
        
    }
    private void StoreData() throws SQLException{
        Connection cnn = newkoneksi();
        String ID = TXID.getText();
        String NM = TXNM.getText();
        String AL = TXAL.getText();
        String ASL = TXASL.getText();
        String TL = TXTLPN.getText();
        if(!cnn.isClosed()){
            PreparedStatement PS = cnn.prepareStatement("INSERT INTO daftar(ID,NAMA,ALAMAT,ASAL_SMA,"
                    + "TELEPON) VALUES(?,?,?,?,?);");
            PS.setString(1, ID);
            PS.setString(2, NM);
            PS.setString(3, AL);
            PS.setString(4, ASL);
            PS.setString(5, TL);
            
            PS.executeUpdate();
        }
    }
    private void UpdateData() throws SQLException{
        Connection cnn= newkoneksi();
        if(!cnn.isClosed()){
            PreparedStatement PS = cnn.prepareStatement("UPDATE daftar SET NAMA=?, ALAMAT=?, ASAL_SMA =?, TELEPON=? WHERE ID=?");
            PS.setString(1, TXNM.getText() );
            PS.setString(2, TXAL.getText() );
            PS.setString(3, TXASL.getText() );
            PS.setString(4, TXTLPN.getText() );  
            PS.setString(5, TXID.getText() );
            PS.executeUpdate();
            cnn.close();
        }
    }
    private void destroyData() throws SQLException{
        Connection cnn = newkoneksi();
        if(!cnn.isClosed()){
            PreparedStatement PS = cnn.prepareStatement("DELETE FROM daftar WHERE ID=?;");
            PS.setString(1, TXID.getText() );
            PS.executeUpdate();
            cnn.close();
        }
    }
    private void kosongkanform(){
        TXID.setText("");
        TXNM.setText("");
        TXAL.setText("");
        TXASL.setText("");
        TXTLPN.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txLabelTEL = new javax.swing.JLabel();
        TXNM = new javax.swing.JTextField();
        TXAL = new javax.swing.JTextField();
        TXASL = new javax.swing.JTextField();
        TXTLPN = new javax.swing.JTextField();
        photo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        BTNTMBH = new javax.swing.JButton();
        BTNEDT = new javax.swing.JButton();
        BTNSELESAI = new javax.swing.JButton();
        BTNHPS = new javax.swing.JButton();
        TXID = new javax.swing.JTextField();
        txLabelASAL = new javax.swing.JLabel();
        txLabelALAMAT = new javax.swing.JLabel();
        txLabelNAMA = new javax.swing.JLabel();
        txLabelID = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("FORM PENDAFTARAN MAHASISWA BARU");

        txLabelTEL.setText("TELPON");

        TXNM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXNMActionPerformed(evt);
            }
        });

        TXAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXALActionPerformed(evt);
            }
        });

        TXASL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXASLActionPerformed(evt);
            }
        });

        TXTLPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTLPNActionPerformed(evt);
            }
        });

        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        BTNTMBH.setText("TAMBAH");
        BTNTMBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTMBHActionPerformed(evt);
            }
        });

        BTNEDT.setText("EDIT");
        BTNEDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDTActionPerformed(evt);
            }
        });

        BTNSELESAI.setText("SELESAI");
        BTNSELESAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSELESAIActionPerformed(evt);
            }
        });

        BTNHPS.setText("HAPUS");
        BTNHPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHPSActionPerformed(evt);
            }
        });

        TXID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXIDActionPerformed(evt);
            }
        });

        txLabelASAL.setText("ASAL SMA/SMK");

        txLabelALAMAT.setText("ALAMAT");

        txLabelNAMA.setText("NAMA");

        txLabelID.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txLabelTEL)
                    .addComponent(txLabelASAL)
                    .addComponent(txLabelNAMA)
                    .addComponent(txLabelALAMAT)
                    .addComponent(txLabelID)
                    .addComponent(BTNTMBH, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BTNEDT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNHPS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNSELESAI, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TXASL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(TXAL, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXNM, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTLPN)
                            .addComponent(TXID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txLabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXNM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txLabelNAMA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txLabelALAMAT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXASL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txLabelASAL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txLabelTEL)
                    .addComponent(TXTLPN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNTMBH, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(BTNEDT, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(BTNSELESAI, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(BTNHPS, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txLabelTEL.getAccessibleContext().setAccessibleName("TELEPON");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXNMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXNMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXNMActionPerformed

    private void TXALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXALActionPerformed

    private void BTNTMBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTMBHActionPerformed
        // TODO add your handling code here:
        if(BTNTMBH.getText().equals("BARU")){
            BTNTMBH.setText("SIMPAN");
            BTNSELESAI.setText("BATAL");
            kosongkanform();
            jTable2.setEnabled(false);
        }else{
            BTNTMBH.setText("BARU");
            BTNSELESAI.setText("SELESAI");
            jTable2.setEnabled(true);
            try {
                StoreData();
                List_All();
            } catch (SQLException ex) {
                Logger.getLogger(FormDMhs.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BTNTMBHActionPerformed

    private void BTNEDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDTActionPerformed
        // TODO add your handling code here:
        try {
            UpdateData();
            List_All();
            
            JOptionPane.showMessageDialog(this, "Data telah diupdate");
            
        } catch (SQLException ex) {
            Logger.getLogger(FormDMhs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNEDTActionPerformed

    private void BTNHPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHPSActionPerformed
        // TODO add your handling code here:
        int jwb = JOptionPane.showOptionDialog(
                this, 
                "Yakin akan menghapus data "+TXNM.getText()+"?", 
                "Hapus Data", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE, 
                null, 
                null, 
                null);
        if(jwb == JOptionPane.YES_OPTION ){
            try {
                destroyData();
                List_All();
            } catch (SQLException ex) {
                Logger.getLogger(FormDMhs.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BTNHPSActionPerformed

    private void TXIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXIDActionPerformed

    private void TXTLPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTLPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTLPNActionPerformed

    private void BTNSELESAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSELESAIActionPerformed
        // TODO add your handling code here:
        if(BTNSELESAI.getText().equals("SELESAI")){
            dispose();
        }else{
            BTNSELESAI.setText("SELESAI");
            BTNTMBH.setText("TAMBAH");
        }
    }//GEN-LAST:event_BTNSELESAIActionPerformed

    private void TXASLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXASLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXASLActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        TXID.setText( jTable2.getValueAt( jTable2.getSelectedRow(),0 ).toString() );
        TXNM.setText( jTable2.getValueAt( jTable2.getSelectedRow(), 1).toString() );
        TXAL.setText( jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString() );
        TXASL.setText( jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString() );
        TXTLPN.setText( jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString() );
        loadphoto(TXID.getText());
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                new FormDMhs().setVisible(true);
            }catch (SQLException ex){
                Logger.getLogger(FormDMhs.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEDT;
    private javax.swing.JButton BTNHPS;
    private javax.swing.JButton BTNSELESAI;
    private javax.swing.JButton BTNTMBH;
    private javax.swing.JTextField TXAL;
    private javax.swing.JTextField TXASL;
    private javax.swing.JTextField TXID;
    private javax.swing.JTextField TXNM;
    private javax.swing.JTextField TXTLPN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel txLabelALAMAT;
    private javax.swing.JLabel txLabelASAL;
    private javax.swing.JLabel txLabelID;
    private javax.swing.JLabel txLabelNAMA;
    private javax.swing.JLabel txLabelTEL;
    // End of variables declaration//GEN-END:variables
}
